services:
  - type: web
    name: junior-goat-website
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 3000
